Render:
  Material:
    # air (or change to light, will make track brighter)
    air_material: air
    # note
    note_material: sea_lantern
    # arctap
    arctap_material: pearlescent_froglight
    # hold
    hold_side_material: light_blue_concrete
    hold_centre_material: sea_lantern
    # red arc
    red_arc_centre_only: false
    red_arc_material: pink_stained_glass
    red_arc_centre_material: glowstone
    red_arc_support_material: pink_stained_glass_pane
    # blue arc
    blue_arc_centre_only: false
    blue_arc_material: blue_stained_glass
    blue_arc_centre_material: sea_lantern
    blue_arc_support_material: blue_stained_glass_pane
    # green arc
    green_arc_centre_only: false
    green_arc_material: lime_stained_glass
    green_arc_centre_material: emerald_block
    green_arc_support_material: lime_stained_glass_pane
    # ground
    track_surface_material: white_concrete
    track_line_material: gray_concrete
    extend_track_surface_material: white_stained_glass
    extend_track_line_material: light_gray_stained_glass
  Position:
    # execute in which dimension
    dimension: void
    # track base: 1 block above the centre of track 0
    ground_x: 1.0
    ground_y: 1.0
    ground_z: -20.0
    ground_interval: 6.0
    # infer distance: distance in front of/behind input line
    track_x_upper_limit: 64.0
    track_x_lower_limit: -10.0
    # all arc raise height (block)
    arc_raise_block: 1.0
    # the height of sky input / ground_interval
    arc_raise_ratio: 1.0
    # note default moving speed (block) per second
    default_speed_per_second: 96.0
  Particle:
    # enable black line render or not
    enable_black_line: true
    # how many particle in a block
    black_line_particle_dense: 0.4
    # enable double-click line render or not
    enable_double_note_line: true
    # how many particle in a block
    double_note_line_particle_dense: 2
  Time:
    # play after last note (tick)
    wait_after_last_note: 100
    # wait before play (tick)
    wait_before_playing: 100
    # block dense of arc which starts as it ends
    zero_time_arc_play_dense: 20
  # don't change this tps on spigot server and its branches unless you want to speed up or slow down the whole render.
  # change this will cause async music and vision without Fabric's Carpet Mod to change TPS.
  tps: 20.0
  # normal pi, hugely change this may cause weird arc
  pi: 3.1415926
Display:
  # control list length of "/arcaea songlist".
  song_number_per_page: 10
  # prefer which language, available: 'en','zh-Hans','zh-Hant','ja','ko'.
  # other unavailable languages will function as 'en'
  language: zh-Hans
File:
  # path of your song folder
  # you'd better not contain space in this path
  execute_path: D:/ProgramData/Datas/arcaea
Info:
  # placeholder is <!>
  song_menu: 歌曲菜单
  argument_type_error: 参数类型错误
  argument_num_error: 参数数量错误
  argument_value_error: 参数数值有误
  aff_file_not_exist: 要访问的谱面文件不存在
  compiling_aff: 正在编译谱面文件，10秒内未编译完成即为超时，请运行/reload confirm
  unable_to_compile: 无法编译，有正在编译的谱面或其他错误
  no_compile_or_not_finished: 无歌曲被编译或编译未完成
  before_play_warning: 歌曲编译完毕，使用/arcaea play confirm来游玩！
  start_play: 启动播放中
  error_occurred_while_starting_play: 启动播放时出现了内部错误
  error_occurred_while_playing: 播放过程中出现了内部错误，请更换谱面或者尝试/reload confirm
  error_occurred_while_compiling: 编译中出现了错误，请更换谱面或者尝试/reload confirm
  compile_finished: 歌曲编译完毕
  play_finished: 播放完毕
Version: 1.0
