Render:
  Material:
    # air (or change to light, will make track brighter)
    air_material: air
    # note
    note_material: sea_lantern
    # arctap
    arctap_material: pearlescent_froglight
    # hold
    hold_side_material: light_blue_concrete
    hold_centre_material: sea_lantern
    # red arc
    red_arc_centre_only: false
    red_arc_material: pink_stained_glass
    red_arc_centre_material: glowstone
    red_arc_support_material: pink_stained_glass_pane
    # blue arc
    blue_arc_centre_only: false
    blue_arc_material: blue_stained_glass
    blue_arc_centre_material: sea_lantern
    blue_arc_support_material: blue_stained_glass_pane
    # green arc
    green_arc_centre_only: false
    green_arc_material: lime_stained_glass
    green_arc_centre_material: emerald_block
    green_arc_support_material: lime_stained_glass_pane
    # ground
    ground_surface_material:
    ground_line_material:
  Position:
    # execute in which dimension
    dimension: void
    # track base: 1 block above the centre of track 0
    ground_x: 1.0
    ground_y: 1.0
    ground_z: -20.0
    ground_interval: 8.0
    # infer distance: distance in front of/behind input line
    track_x_upper_limit: 150.0
    track_x_lower_limit: -10.0
    # all arc raise height (block)
    arc_raise_block: 1.0
    # the height of sky input / ground_interval
    arc_raise_ratio: 1.0
    # note default moving speed (block) per second
    default_speed_per_second: 200.0
  Time:
    # play after last note (tick)
    wait_after_last_note: 100
    # wait before play (tick)
    wait_before_playing: 100
    # block dense of arc which starts as it ends
    zero_time_arc_play_dense: 20
  # don't change this tps on spigot server and its branches unless you want to speed up or slow down the whole render.
  # change this will cause async music and vision without Fabric's Carpet Mod to change TPS.
  tps: 20.0
  # normal pi, change this will cause weird arc
  pi: 3.1415926
Display:
  # control list length of "/arcaea songlist".
  song_number_per_page: 10
  # prefer which language, available: 'en','zh-Hans','zh-Hant','ja','ko'.
  # other unavailable languages will function as 'en'
  language: zh-Hans
File:
  # path of your song folder
  # you'd better not contain space in this path
  execute_path: F:/arcaea
Version: 1.0
